linters:
  disable-all: true
  enable:
    - errcheck # Ensures errors are handled
    - gosimple # Simplifies Go code
    - govet # Reports potential issues, including alignment
    - ineffassign # Detects unused assignments
    - staticcheck # Replaces gosimple, unused, etc., with enhanced checks
    - unused # Detects unused variables/functions (includes structcheck/varcheck, replaces deadcode)
    - bodyclose # Ensures HTTP response bodies are closed
    - contextcheck # Ensures correct context usage
    - cyclop # Complexity linter
    - durationcheck # Ensures correct time duration usage
    - errname # Consistent error variable naming
    - errorlint # Safer error type assertions
    - goimports # Ensures imports are formatted correctly
    - gosec # Security linter
    - gocritic # Code quality linter

linters-settings:
  cyclop:
    max-complexity: 15 # Set desired max complexity

  gocritic:
    disabled-checks:
      - singleCaseSwitch # Disable specific check

issues:
  exclude-rules:
    - path: "."
      linters:
        - typecheck # Exclude typecheck from all paths
